language: node_js
node_js:
- '8'
- '10'
script:
- npm run coverage
- npm run build
after_success: npm run coveralls
deploy:
  provider: gcs
  skip_cleanup: true
  local_dir: build
  access_key_id: GOOGXYINYD7IGK33XTPS
  secret_access_key:
    secure: nLYCfKJuOyQDViOG8VxXRexKync9neRa7NSanwyhHnsXylBVTscKAthqUO8m9jT+KgT14AVLu+VJRGBEHqaSOoGigELCqVjd57iVvcWNuNzjibshN2egkqM3r86msMtNmwwh6vMJadLx1DHk7sWVXnHtCwgqeC6a+fnQUGkbuzHYcP6MljNsFWOYDetgseH9f7yN4ka0a4XDo34fIZmiDwBiTtHbyr9yO7EQ+NSNbnoIF8gpZ2870/3nI2zh1ypejGVbFJ/12ihgUfGEskxUgOnhMeIsiUjwpfJC2qHeS9XPlbvCgw+MUB54xIIXsnF49D0Y/9SOOgRZi7DSFAdrHQ01sgZat3zkc+xn8H6uNT5TxfrnviPjAvjnvwPD2aY9yKt9dfcA7KgxhrVO7hRXBcbY25xoDxpXJ/N0g3Hc0XZJRewrQCix85p4tAvjy7o1o27s5Q8bK4cK3ZwjruS/gxDA1+VjVTgrmhOEz4/+86cdETw90aPy6jN2AuA2UjGVvRzVi+dKqtKL6i1UT7DkBCm+SbFGuU4hRyWDjKvIoUIYR7o7kQvZeBtFYZHpttSM/x6tMzPvUTG3Vg4jcc8YZ6iR1U2QduhImYfShmA6K4BT+qmPkwNnsPJKfLnDJcN6eLJMhUsHXdRqdOeyEfvn0gh31cT8vuyjlIYwoeLrusA=
  bucket: www.spotifight.me
  on:
    repo: joncass/spotifight
    branch: master
